In [2]:
x = 1
y = 2
x+ y

3

In [3]:
x

1

In [1]:
def add_numbers(x, y):
    return x + y

add_numbers(1,10)

11

In [2]:
type(1)

int

In [3]:
x=(1, 'a')
type(x)

tuple

In [4]:
x=[1, 'a', 'b']
type(x)

list

In [5]:
x.append(50)
print(x)

[1, 'a', 'b', 50]


In [7]:
x.pop()
print(x)

[1, 'a']


In [9]:
for item in x:
    print(item)

1
a


In [4]:
st = 'this is a string'
print(st[0:2])

th


In [6]:
x = 'Dr. Christopher Brooks'

print(x[4:15])

Christopher


# Numpy

In [13]:
import numpy as np

# Creating Arrays

In [16]:
mylist = [1, 2, 3]
print(mylist)
x= np.array(mylist)
x

[1, 2, 3]


array([1, 2, 3])

In [17]:
y = np.array([ 4, 5, 6 ])
y

array([4, 5, 6])

In [24]:
m = np.array([[7,8,9], [10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [25]:
m.shape

(2, 3)

In [30]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [33]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [34]:
['a', 'b', 'c'] + [1, 2, 3]


['a', 'b', 'c', 1, 2, 3]

In [35]:
type(lambda x: x+1)

function

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
arr[::3]

array([1, 4, 7])